ebd/helpers: initial new* ipc support

diff --git a/ebd/helpers/common/pkgcore-ebuild-helper b/ebd/helpers/common/pkgcore-ebuild-helper
--- a/ebd/helpers/common/pkgcore-ebuild-helper
+++ b/ebd/helpers/common/pkgcore-ebuild-helper
@@ -27,88 +27,10 @@ source "${PKGCORE_EBD_PATH}"/eapi/depend.bash >&2 || \
 	die "failed sourcing eapi/depend.bash"
 source "${PKGCORE_EBD_PATH}"/eapi/common.bash >&2 || \
 	die "failed sourcing eapi/common.bash"
+source "${PKGCORE_EBD_PATH}"/helpers/internals/helper-lib.bash >&2 || \
+	die "failed sourcing helpers/internals/helper-lib.bash"
 
 failed=false
-_helper_issues=()
-error() {
-	echo "${HELPER_ERROR_PREFIX}: ${@-no message given}" >&2
-	_helper[${#_helper[@]}]=${*-no message given}
-	failed=true
-}
-
-warn() {
-	echo "${HELPER_ERROR_PREFIX}: warning, ${@-no message given}" >&2
-}
-
-info() {
-	echo "${HELPER_ERROR_PREFIX}: $@" >&2
-}
-
-check_args() {
-	local tense="argument"
-	local min=$(( $1 ))
-	local max
-	[[ ${min} -gt 1 ]] && tense="arguments"
-	if [[ $2 == '-' ]]; then
-		max=${HELPER_ARG_COUNT}
-	elif [[ -z $2 ]]; then
-		max=$1
-	fi
-	max=$(( max ))
-
-	if [[ ${HELPER_ARG_COUNT} -ge ${min} && ${HELPER_ARG_COUNT} -le ${max} ]]; then
-		return 0
-	fi
-	if [[ ${min} -eq ${max} ]]; then
-		die "${HELPER_ERROR_PREFIX}: requires exactly ${min} ${tense}, got ${HELPER_ARG_COUNT}"
-	elif [[ $2 == '-' ]]; then
-		die "${HELPER_ERROR_PREFIX}: requires at least ${min} ${tense}, got ${HELPER_ARG_COUNT}"
-	else:
-		die "${HELPER_ERROR_PREFIX}: requires at least ${min} ${tense}, and at most ${max} arguments, got ${HELPER_ARG_COUNT}"
-	fi
-}
-
-check_command() {
-	local ret
-	"$@"
-	ret=$?
-	[[ ${ret} == 0 ]] && return 0
-	error "exitcode ${ret} from $*"
-	return $(( ret ))
-}
-
-check_command_or_stop() {
-	check_command "$@"
-	__helper_check_exit $? "$@ failed, cannot continue"
-	return 0
-}
-
-__helper_exit() {
-	[[ $1 == 0 ]] && exit 0
-
-	local ret=$1
-	local error_msg="${HELPER_ERROR_PREFIX}: exitcode ${ret}"
-	shift
-	[[ -n $@ ]] && error_msg+=": $@"
-
-	if ${PKGCORE_NONFATAL}; then
-		eerror "${error_msg}"
-		exit ${ret}
-	fi
-
-	die "${error_msg}"
-}
-
-__helper_failed() {
-	PKGCORE_IS_NOT_HELPER=
-	die "helper failed: ${BASH_COMMAND}"
-}
-
-__helper_check_exit() {
-	[[ $1 == 0 ]] && return
-	shift
-	__helper_exit "$@"
-}
 
 MASTER_HELPER_NAME=${1##*/}
 HELPER_ERROR_PREFIX=
diff --git a/ebd/helpers/common/pkgcore-ipc-helper b/ebd/helpers/common/pkgcore-ipc-helper
--- a/ebd/helpers/common/pkgcore-ipc-helper
+++ b/ebd/helpers/common/pkgcore-ipc-helper
@@ -27,6 +27,8 @@ source "${PKGCORE_EBD_PATH}"/eapi/depend.bash >&2 || \
 	die "failed sourcing eapi/depend.bash"
 source "${PKGCORE_EBD_PATH}"/eapi/common.bash >&2 || \
 	die "failed sourcing eapi/common.bash"
+source "${PKGCORE_EBD_PATH}"/helpers/internals/helper-lib.bash >&2 || \
+	die "failed sourcing helpers/internals/helper-lib.bash"
 
 HELPER_ERROR_PREFIX=
 
@@ -40,6 +42,7 @@ fi
 # run an ebuild command on the python side and return its status
 __ebd_ipc_cmd() {
 	local cmd=$1 opts=$2 ret_str
+	local -a ret
 	shift 2
 
 	__ebd_write_line ${cmd}
@@ -50,44 +53,22 @@ __ebd_ipc_cmd() {
 	printf "%s\0" "$@" >&${PKGCORE_EBD_WRITE_FD}
 	__ebd_write_line
 
-	__ebd_read_line ret_str
-	__ipc_exit "${ret_str}"
-}
-
-__ipc_exit() {
-	[[ $1 == 0 ]] && exit 0
-
-	local ret_str=$1 ret msg
-	local -a ret_array
-
 	# Split return status into array of return code and optional error message.
 	# This uses a bell char as a delimiter since the null char can't be
 	# assigned to variables.
-	IFS=$'\x07' read -ra ret_array <<< "${ret_str}"
-	ret=${ret_array[0]}
-	msg=${ret_array[1]}
-
-	local error_msg="${HELPER_ERROR_PREFIX}: exitcode ${ret}"
-	[[ -n ${msg} ]] && error_msg+=": ${msg}"
-
-	if ${PKGCORE_NONFATAL}; then
-		eerror "${error_msg}"
-		exit ${ret}
-	fi
-
-	die "${error_msg}"
+	__ebd_read_line ret_str
+	IFS=$'\x07' read -ra ret <<< "${ret_str}"
+	__helper_exit "${ret[@]}"
 }
 
 run_ipc_cmd() {
 	[[ $# -eq 0 ]] && die "${FUNCNAME}: missing required arguments"
-
 	local HELPER_PATH=$1
 	local HELPER_NAME=${1##*/}
 	local HELPER_EAPI=${1%/*}
 	HELPER_EAPI=${HELPER_EAPI##*/}
-	local IPC_CMD=${HELPER_NAME}
 	shift
-
+	local HELPER_ARG_COUNT=$#
 	if [[ ! -e ${HELPER_PATH} ]]; then
 		# note this can daftly go find a binary...
 		HELPER_PATH=$(type -p "${HELPER_NAME}")
@@ -97,7 +78,9 @@ run_ipc_cmd() {
 	local OLD_ERROR_PREFIX=${HELPER_ERROR_PREFIX}
 	local HELPER_ERROR_PREFIX=${OLD_ERROR_PREFIX:+${OLD_ERROR_PREFIX}: }${HELPER_NAME}
 
+	local IPC_CMD=${HELPER_NAME}
 	source "${HELPER_PATH}"
+
 	# load main command opts when running a subcommand
 	if [[ ${HELPER_NAME} != ${IPC_CMD} ]]; then
 		source "$(type -p ${IPC_CMD})" >&2 || die "failed sourcing ${IPC_CMD}"
