add initial importation of exit functionality

diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/_generic_new b/pkgcore/ebuild/eapi-bash/helpers/common/_generic_new
--- a/pkgcore/ebuild/eapi-bash/helpers/common/_generic_new
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/_generic_new
@@ -2,6 +2,8 @@
 # Copyright 2011 Brian Harring <ferringb@gmail.com>
 # License: GPLv2 or bsd-3
 
+source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+
 if [[ -z ${T} ]]; then
 	echo "$0: \${T} isn't defined" >&2
 	exit 2
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/dolib b/pkgcore/ebuild/eapi-bash/helpers/common/dolib
--- a/pkgcore/ebuild/eapi-bash/helpers/common/dolib
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/dolib
@@ -2,6 +2,8 @@
 # Copyright 1999-2006 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
+source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+
 # Setup ABI cruft
 LIBDIR_VAR="LIBDIR_${ABI}"
 if [[ -n ${ABI} && -n ${!LIBDIR_VAR} ]] ; then
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/doman b/pkgcore/ebuild/eapi-bash/helpers/common/doman
--- a/pkgcore/ebuild/eapi-bash/helpers/common/doman
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/doman
@@ -2,6 +2,8 @@
 # Copyright 1999-2006 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
+source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+
 if [ -z "${PKGCORE_BIN_PATH}" ]; then
 	echo "PKGCORE_BIN_PATH is unset!"
 	exit -1
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/prepallstrip b/pkgcore/ebuild/eapi-bash/helpers/common/prepallstrip
--- a/pkgcore/ebuild/eapi-bash/helpers/common/prepallstrip
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/prepallstrip
@@ -2,6 +2,8 @@
 # Copyright 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
+source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+
 if [ "${FEATURES//*nostrip*/true}" == "true" ] || [ "${RESTRICT//*nostrip*/true}" == "true" ] ; then
 	exit 0
 fi
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/preplib b/pkgcore/ebuild/eapi-bash/helpers/common/preplib
--- a/pkgcore/ebuild/eapi-bash/helpers/common/preplib
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/preplib
@@ -2,6 +2,8 @@
 # Copyright 1999-2004 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
+source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+
 LIBDIR_VAR="LIBDIR_${ABI}"
 if [ -n "${ABI}" -a -n "${!LIBDIR_VAR}" ]; then
 	CONF_LIBDIR="${!LIBDIR_VAR}"
