refactor helpers, adding die support for eapi4
specifically, make use of the new helper functionality, and tighten
up the error checking.

diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/doexe b/pkgcore/ebuild/eapi-bash/helpers/common/doexe
--- a/pkgcore/ebuild/eapi-bash/helpers/common/doexe
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/doexe
@@ -8,23 +8,31 @@ if [ -z "${PKGCORE_BIN_PATH}" ]; then
 	echo "PKGCORE_BIN_PATH is unset!"
 	exit -1
 fi
-source "${PKGCORE_BIN_PATH}/isolated-functions.lib" || {
-	"failed sourcing isolated-function.sh"; exit 1;
-}
 
 if [[ $# -lt 1 ]] ; then
-	echo "$0: at least one argument needed" 1>&2
-	exit 1
+	pkgcore_helper_exit 1 "at least one arguement needed"
 fi
 
 if [[ ! -d ${D}${EXEDESTTREE} ]] ; then
 	install -d "${D}${EXEDESTTREE}"
+	pkgcore_helper_check_exit $? "install of base directory failed; \${D}=${D}, \${EXEDESTTREE}=${EXEDESTTREE}"
 fi
 
+ret=0
 for x in "$@" ; do
 	if [ -L "${x}" ] ; then
-		cp "${x}" "${T}"
+		if ! cp "${x}" "${T}"; then
+			echo "warning, cp to temp space failed, skipping" >&2
+			((ret|=1))
+			continue
+		fi
+
 		mysrc="${T}"/$(/usr/bin/basename "${x}")
+		if [ $? != 0 ]]; then
+			echo "warning: basename failed for ${x}; skipping" >&2
+			((ret|=1))
+			continue
+		fi
 	elif [ -d "${x}" ] ; then
 		echo "doexe: warning, skipping directory ${x}"
 		continue
@@ -32,4 +40,7 @@ for x in "$@" ; do
 		mysrc="${x}"
 	fi
 	install ${EXEOPTIONS} "${mysrc}" "${D}${EXEDESTTREE}"
+	((ret|=$?))
 done
+
+pkgcore_helper_exit $ret
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/dosed b/pkgcore/ebuild/eapi-bash/helpers/common/dosed
--- a/pkgcore/ebuild/eapi-bash/helpers/common/dosed
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/dosed
@@ -2,22 +2,29 @@
 # Copyright 1999-2006 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
+shopt -s extdebug
 source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
 
 mysed="s:${D}::g"
 
+ret=0
 for x in "$@" ; do
 	y="${D}${x}"
 	if [ -e "${y}" ] ; then
 		if [ -f "${y}" ] ; then
 			mysrc="${T}/${y##*/}"
 			cp "${y}" "${mysrc}"
+			((ret|=$?))
 			sed -e "${mysed}" "${mysrc}" > "${y}"
+			((ret|=$?))
 		else
-			echo "${y} is not a regular file!"
-			exit 1
+			echo "${y} is not a regular file!" >&2
+			((ret|=1))
 		fi
 	else
-		mysed="${x}"
+		echo "file '${x}' not found" >&2
+		((ret|=1))
 	fi
 done
+
+pkgcore_helper_exit ${ret}
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/prepalldocs b/pkgcore/ebuild/eapi-bash/helpers/common/prepalldocs
--- a/pkgcore/ebuild/eapi-bash/helpers/common/prepalldocs
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/prepalldocs
@@ -2,6 +2,7 @@
 # Copyright 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
+shopt -s extdebug
 source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
 
 dir="${D}usr/share/doc"
@@ -24,7 +25,7 @@ if [ -z "${PORTAGE_COMPRESS_SUFFIX}" ] ; then
 	case ${PORTAGE_COMPRESS} in
 		gzip)  suffix="gz";;
 		bzip2) suffix="bz2";;
-		*)     echo "prepalldocs error: please set PORTAGE_COMPRESS_SUFFIX in make.conf" 1>&2
+		*)     echo "prepalldocs error: please set PORTAGE_COMPRESS_SUFFIX in make.conf" >&2
 		       exit 1;;
 	esac
 fi
@@ -52,8 +53,10 @@ for y in ${z} ; do
 		fi
 	else
 		if [ "${y##*.}" != "${suffix}" ] ; then
-			echo "   compressing ${y##*/}"
+			echo "   compressing ${y##*/}" >&2
 			"${PORTAGE_COMPRESS}" ${PORTAGE_COMPRESS_FLAGS} -f "${y}"
 		fi
 	fi
 done
+
+:
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo b/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo
--- a/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo
@@ -2,6 +2,7 @@
 # Copyright 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
+shopt -s extdebug
 source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
 
 if [ -z "$1" ] ; then
@@ -24,7 +25,7 @@ if [ -z "${PORTAGE_COMPRESS_SUFFIX}" ] ; then
 	case ${PORTAGE_COMPRESS} in
 		gzip)  suffix="gz";;
 		bzip2) suffix="bz2";;
-		*)     echo "prepinfo: error fixing links: please set PORTAGE_COMPRESS_SUFFIX in make.conf" 1>&2
+		*)     echo "prepinfo: error fixing links: please set PORTAGE_COMPRESS_SUFFIX in make.conf" >&2
 		       exit 1;;
 	esac
 fi
@@ -57,3 +58,5 @@ for x in `find "${z}"/ \( -type f -or -type l \) -maxdepth 1 -mindepth 1 2>/dev/
 		fi
 	fi
 done
+
+:
