standardize helpers on ED rather than D
Add appropriate checks to the shebang helper to force ED=${D} if prefix
isn't supported; primarily to block ebuilds from trying to be 'smart'.

diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper b/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper
--- a/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper
@@ -88,6 +88,13 @@ check_command_or_stop()
 MASTER_HELPER_NAME=${1##*/}
 HELPER_ERROR_PREFIX=
 
+if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
+	export ED="${D}"
+elif [[ "${ED:-unset}" == unset ]]; then
+	error "prefix mode is enabled, but ED can't be found.  Ebuild bug?"
+	exit 1
+fi
+
 invoke_script()
 {
 	[[ $# == 0 ]] && die "internal error: invoke_script invoked incorrectly"
diff --git a/pkgcore/ebuild/eapi-bash/helpers/internals/prepall b/pkgcore/ebuild/eapi-bash/helpers/internals/prepall
--- a/pkgcore/ebuild/eapi-bash/helpers/internals/prepall
+++ b/pkgcore/ebuild/eapi-bash/helpers/internals/prepall
@@ -9,19 +9,26 @@ source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; 
 prepinfo
 prepallstrip
 
+if ! ${PKGCORE_PREFIX_SUPPORT=false}; then
+	export ED="${D}"
+elif [[ "${ED:-unset}" == "unset" ]]; then
+	echo "The variable ED is missing from the environemnt of prepall; failing."
+	exit -1
+fi
+
 # this should help to ensure that all (most?) shared libraries are executable
 # and that all libtool scripts / static libraries are not executable
-for i in "${D}"opt/*/lib{,32,64} \
-		"${D}"lib{,32,64}       \
-		"${D}"usr/lib{,32,64}   \
-		"${D}"usr/X11R6/lib{,32,64} ; do
+for i in "${ED}"opt/*/lib{,32,64} \
+		"${ED}"lib{,32,64}       \
+		"${ED}"usr/lib{,32,64}   \
+		"${ED}"usr/X11R6/lib{,32,64} ; do
 	[[ ! -d ${i} ]] && continue
 
 	for j in "${i}"/*.so.* "${i}"/*.so ; do
 		[[ ! -e ${j} ]] && continue
 		[[ -L ${j} ]] && continue
 		[[ -x ${j} ]] && continue
-		echo "making executable: /${j/${D}/}"
+		echo "making executable: /${j/${ED}/}"
 		chmod +x "${j}"
 	done
 
@@ -29,7 +36,7 @@ for i in "${D}"opt/*/lib{,32,64} \
 		[[ ! -e ${j} ]] && continue
 		[[ -L ${j} ]] && continue
 		[[ ! -x ${j} ]] && continue
-		echo "removing executable bit: /${j/${D}/}"
+		echo "removing executable bit: /${j/${ED}/}"
 		chmod -x "${j}"
 	done
 done
@@ -38,7 +45,7 @@ done
 # /lib, we have to make sure we have a linker script in /usr/lib along side
 # the static library, or gcc will utilize the static lib when linking :(.
 # http://bugs.gentoo.org/4411
-for a in "${D}"usr/lib*/*.a ; do
+for a in "${ED}"usr/lib*/*.a ; do
 	s=${a%.a}.so
 	if [[ ! -e ${s} ]] ; then
 		s=${s%usr/*}${s##*/usr/}
@@ -50,17 +57,17 @@ for a in "${D}"usr/lib*/*.a ; do
 done
 
 # Make sure people don't store libtool files or static libs in /lib
-f=$(ls "${D}"lib*/*.{a,la} 2>/dev/null)
+f=$(ls "${ED}"lib*/*.{a,la} 2>/dev/null)
 if [[ -n ${f} ]] ; then
 	echo -e "\n\aQA Notice: excessive files found in the / partition\a"
 	echo "${f}"
 	sleep 1
 fi
 
-# Verify that the libtool files don't contain bogus $D entries.
-for a in "${D}"usr/lib*/*.la ; do
+# Verify that the libtool files don't contain bogus $ED entries.
+for a in "${ED}"usr/lib*/*.la ; do
 	s=${a##*/}
-	if grep -qs "${D}" "${a}" ; then
+	if grep -qs "${ED}" "${a}" ; then
 		echo -e "\n\aQA Notice: ${s} appears to contain PORTAGE_TMPDIR paths\a"
 		sleep 1
 	fi
@@ -69,7 +76,7 @@ done
 if type -p scanelf > /dev/null ; then
 
 # Run some sanity checks on shared libraries
-for d in "${D}"lib* "${D}"usr/lib* ; do
+for d in "${ED}"lib* "${ED}"usr/lib* ; do
 	f=$(scanelf -ByF '%S %p' "${d}"/lib*.so* | gawk '$2 == "" { print }')
 	if [[ -n ${f} ]] ; then
 		echo -e "\n\aQA Notice: the following shared libraries lack a SONAME\a"
diff --git a/pkgcore/ebuild/eapi-bash/helpers/internals/prepallman b/pkgcore/ebuild/eapi-bash/helpers/internals/prepallman
--- a/pkgcore/ebuild/eapi-bash/helpers/internals/prepallman
+++ b/pkgcore/ebuild/eapi-bash/helpers/internals/prepallman
@@ -5,7 +5,14 @@
 shopt -s extdebug
 source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
 
-for x in $(find "${D}" -name man -type d -printf '%P\n') ; do
+if ! ${PKGCORE_PREFIX_SUPPORT=false}; then
+	export ED="${D}"
+elif [[ "${ED-unset}" == "unset" ]]; then
+	echo "The ED variable was missing from the environment, but is required for prefix mode.  Failing".
+	exit -1
+fi
+
+for x in $(find "${ED}" -name man -type d -printf '%P\n') ; do
 	prepman ${x%/man}
 	export prepallman_banner=no
 done
