make info function output to stderr
Its only consumer (emake) gets called via command substitution in the
toolchain eclass which breaks when the info output is sent to stdout as
well.

diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper b/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper
--- a/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper
@@ -40,7 +40,7 @@ warn()
 
 info()
 {
-	echo "${HELPER_ERROR_PREFIX}: $@"
+	echo "${HELPER_ERROR_PREFIX}: $@" >&2
 }
 
 check_args()
