style(bash): initial work towards a more consistent bash style

diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper b/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper
--- a/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/pkgcore-ebuild-helper
@@ -12,74 +12,68 @@ if [[ -z ${PKGCORE_BIN_PATH} ]]; then
 fi
 export PKGCORE_BIN_PATH
 
-source "${PKGCORE_BIN_PATH}/exit-handling.lib" || {
+source "${PKGCORE_BIN_PATH}"/exit-handling.lib || {
 	echo "failed to load exit-handling library: PKGCORE_BIN_PATH=${PKGCORE_BIN_PATH}" >&2
-	exit -127;
+	exit -127
 }
 
 if [[ $# -lt 1 ]]; then
 	die "ebuild-helper invoked without a target helper; no args given."
 fi
 
-source "${PKGCORE_BIN_PATH}/isolated-functions.lib" || \
+source "${PKGCORE_BIN_PATH}"/isolated-functions.lib || \
 	die "failed to load isolated-functions.lib"
 
 failed=false
-_helper_issues=( )
-error()
-{
+_helper_issues=()
+error() {
 	echo "${HELPER_ERROR_PREFIX}: ${@-no message given}" >&2
-	_helper[${#_helper[@]}]="${*-no message given}"
+	_helper[${#_helper[@]}]=${*-no message given}
 	failed=true
 }
 
-warn()
-{
+warn() {
 	echo "${HELPER_ERROR_PREFIX}: warning, ${@-no message given}" >&2
 }
 
-info()
-{
+info() {
 	echo "${HELPER_ERROR_PREFIX}: $@" >&2
 }
 
-check_args()
-{
+check_args() {
 	local tense="argument"
 	local min=$(( $1 ))
 	local max
-	[[ $min -gt 1 ]] && tense="arguments"
-	if [[ $2 == - ]]; then
+	[[ ${min} -gt 1 ]] && tense="arguments"
+	if [[ $2 == '-' ]]; then
 		max=${HELPER_ARG_COUNT}
 	elif [[ -z $2 ]]; then
-		max=${1}
+		max=$1
 	fi
-	max=$(( ${max} ))
+	max=$(( max ))
 
 	if [[ ${HELPER_ARG_COUNT} -ge ${min} ]] && [[ ${HELPER_ARG_COUNT} -le ${max} ]]; then
-		return 0;
+		return 0
 	fi
-	if [[ $min == $max ]]; then
+	if [[ ${min} -eq ${max} ]]; then
 		die "${HELPER_ERROR_PREFIX}: requires exactly ${min} ${tense}, got ${HELPER_ARG_COUNT}"
-	elif [[ ${2} == - ]]; then
+	elif [[ $2 == '-' ]]; then
 		die "${HELPER_ERROR_PREFIX}: requires at least ${min} ${tense}, got ${HELPER_ARG_COUNT}"
 	else:
 		die "${HELPER_ERROR_PREFIX}: requires at least ${min} ${tense}, and at most ${max} arguments, got ${HELPER_ARG_COUNT}"
 	fi
 }
 
-check_command()
-{
+check_command() {
 	local ret
 	"$@"
 	ret=$?
-	[[ $ret == 0 ]] && return 0
-	error "exitcode $ret from $*"
-	return $(( $ret ))
+	[[ ${ret} == 0 ]] && return 0
+	error "exitcode ${ret} from $*"
+	return $(( ret ))
 }
 
-check_command_or_stop()
-{
+check_command_or_stop() {
 	check_command "$@"
 	__helper_check_exit $? "$@ failed, cannot continue"
 	return 0
@@ -89,19 +83,18 @@ MASTER_HELPER_NAME=${1##*/}
 HELPER_ERROR_PREFIX=
 
 if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
-	export ED="${D}"
-elif [[ "${ED:-unset}" == unset ]]; then
+	export ED=${D}
+elif [[ ${ED:-unset} == "unset" ]]; then
 	error "The variable ED is missing from the environment, but is required for prefix mode; failing."
 	exit -1
 fi
 
-invoke_script()
-{
-	[[ $# == 0 ]] && die "internal error: invoke_script invoked incorrectly"
-	local HELPER_PATH="${1}"
+invoke_script() {
+	[[ $# -eq 0 ]] && die "internal error: invoke_script invoked incorrectly"
+	local HELPER_PATH=$1
 	local HELPER_NAME=${1##*/}
 	shift
-	local HELPER_ARG_COUNT="$#"
+	local HELPER_ARG_COUNT=$#
 	if [[ ! -e ${HELPER_PATH} ]]; then
 		# note this can daftly go find a binary...
 		HELPER_PATH=$(type -p "${HELPER_NAME}")
@@ -109,12 +102,12 @@ invoke_script()
 	fi
 
 	local OLD_ERROR_PREFIX=${HELPER_ERROR_PREFIX}
-	local HELPER_ERROR_PREFIX="${OLD_ERROR_PREFIX:+${OLD_ERROR_PREFIX}: }${HELPER_NAME}"
+	local HELPER_ERROR_PREFIX=${OLD_ERROR_PREFIX:+${OLD_ERROR_PREFIX}: }${HELPER_NAME}
 
 	source "${HELPER_PATH}"
 
-	if $failed; then
-		if [[ -n ${PKGCORE_NONFATAL_HELPER} ]]; then
+	if ${failed}; then
+		if ${PKGCORE_NONFATAL_HELPER}; then
 			echo "WARNING: nonzero exitcode from ${HELPER_ERROR_PREFIX}" >&2
 			# need to track the exit code here...
 			return 1
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/prepalldocs b/pkgcore/ebuild/eapi-bash/helpers/common/prepalldocs
--- a/pkgcore/ebuild/eapi-bash/helpers/common/prepalldocs
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/prepalldocs
@@ -3,18 +3,18 @@
 # Distributed under the terms of the GNU General Public License v2
 
 shopt -s extdebug
-source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+source "${PKGCORE_BIN_PATH}"/exit-handling.lib || { echo "failed loading libs"; exit -127; }
 
 if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
-	ED="${D}"
-elif [[ "${ED:-unset}" == "unset" ]]; then
+	ED=${D}
+elif [[ ${ED:-unset} == "unset" ]]; then
 	echo "The variable ED is missing from the environment, but is required for prefix mode; failing."
 	exit -1
 fi
 
-dir="${ED}usr/share/doc"
+dir=${ED}usr/share/doc
 
-[[ ! -d "${dir}" ]] && exit 0
+[[ ! -d ${dir} ]] && exit 0
 
 z=$(find "${dir}" -print \
 	'(' -type f -or -type l ')' \
@@ -25,9 +25,9 @@ z=$(find "${dir}" -print \
 	-not -name '*.js' \
 	2>/dev/null)
 
-[[ -z "${z}" ]] && exit 0
+[[ -z ${z} ]] && exit 0
 
-if [[ -z "${PORTAGE_COMPRESS_SUFFIX}" ]]; then
+if [[ -z ${PORTAGE_COMPRESS_SUFFIX} ]]; then
 	case ${PORTAGE_COMPRESS} in
 		gzip)  suffix="gz";;
 		bzip2) suffix="bz2";;
@@ -39,27 +39,27 @@ fi
 
 IFS=$'\n'
 echo "doc: ${PORTAGE_COMPRESS} ${PORTAGE_COMPRESS_FLAGS}"
-for y in ${z} ; do
-	if [[ -L "${y}" ]]; then
+for y in ${z}; do
+	if [[ -L ${y} ]]; then
 		# Symlink ...
 		mylink=${y}
 		linkto=$(readlink "${y}")
 
-		if [[ "${linkto##*.}" != "${suffix}" ]]; then
-			linkto="${linkto}.${suffix}"
+		if [[ ${linkto##*.} != ${suffix} ]]; then
+			linkto=${linkto}.${suffix}
 		fi
-		if [[ "${mylink##*.}" != "${suffix}" ]]; then
-			mylink="${mylink}.${suffix}"
+		if [[ ${mylink##*.} != ${suffix} ]]; then
+			mylink=${mylink}.${suffix}
 		fi
 
 		echo "   link fixed ${mylink##*/}"
 		ln -snf "${linkto}" "${mylink}"
-		if [[ "${y}" != "${mylink}" ]]; then
+		if [[ ${y} != ${mylink} ]]; then
 			echo "   link removed ${y##*/}"
 			rm -f "${y}"
 		fi
 	else
-		if [[ "${y##*.}" != "${suffix}" ]]; then
+		if [[ ${y##*.} != ${suffix} ]]; then
 			echo "   compressing ${y##*/}" >&2
 			"${PORTAGE_COMPRESS}" ${PORTAGE_COMPRESS_FLAGS} -f "${y}"
 		fi
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo b/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo
--- a/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo
@@ -4,30 +4,30 @@
 # Distributed under the terms of the GNU General Public License v2
 
 shopt -s extdebug
-source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+source "${PKGCORE_BIN_PATH}"/exit-handling.lib || { echo "failed loading libs"; exit -127; }
 
 if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
-	ED="${D}"
-elif [[ "${ED:-unset}" == "unset" ]]; then
+	ED=${D}
+elif [[ ${ED:-unset} == "unset" ]]; then
 	echo "The variable ED is missing from the environment, but is required for prefix mode; failing."
 	exit -1
 fi
 
-if [[ -z "$1" ]]; then
-	z="${ED}usr/share/info"
+if [[ -z $1 ]]; then
+	z=${ED}usr/share/info
 else
-	if [[ -d "${ED}$1/share/info" ]]; then
-		z="${ED}$1/share/info"
+	if [[ -d ${ED}$1/share/info ]]; then
+		z=${ED}$1/share/info
 	else
-		z="${ED}$1/info"
+		z=${ED}$1/info
 	fi
 fi
 
-[[ ! -d "${z}" ]] && exit 0
+[[ ! -d ${z} ]] && exit 0
 
 rm -f "${z}"/dir{,.old}{,.info{,.gz,.bz2,.xz,.Z}}
 
-if [[ -z "${PORTAGE_COMPRESS_SUFFIX}" ]]; then
+if [[ -z ${PORTAGE_COMPRESS_SUFFIX} ]]; then
 	case ${PORTAGE_COMPRESS} in
 		gzip)  suffix="gz";;
 		bzip2) suffix="bz2";;
@@ -39,27 +39,27 @@ fi
 
 echo "info: ${PORTAGE_COMPRESS} ${PORTAGE_COMPRESS_FLAGS}"
 
-for x in `find "${z}"/ \( -type f -or -type l \) -maxdepth 1 -mindepth 1 2>/dev/null` ; do
-	if [[ -L "${x}" ]]; then
+for x in $(find "${z}"/ \( -type f -or -type l \) -maxdepth 1 -mindepth 1 2>/dev/null); do
+	if [[ -L ${x} ]]; then
 		# Symlink ...
 		mylink=${x}
 		linkto=$(readlink "${x}")
 
-		if [[ "${linkto##*.}" != "${suffix}" ]]; then
-			linkto="${linkto}.${suffix}"
+		if [[ ${linkto##*.} != ${suffix} ]]; then
+			linkto=${linkto}.${suffix}
 		fi
-		if [[ "${mylink##*.}" != "${suffix}" ]]; then
-			mylink="${mylink}.${suffix}"
+		if [[ ${mylink##*.} != ${suffix} ]]; then
+			mylink=${mylink}.${suffix}
 		fi
 
 		echo "   fixing GNU info symlink: ${mylink##*/}"
 		ln -snf "${linkto}" "${mylink}"
-		if [[ "${x}" != "${mylink}" ]]; then
+		if [[ ${x} != ${mylink} ]]; then
 			echo "   removing old symlink: ${x##*/}"
 			rm -f "${x}"
 		fi
 	else
-		if [[ "${x##*.}" != "${suffix}" ]]; then
+		if [[ ${x##*.} != ${suffix} ]]; then
 			echo "   compressing GNU info page: ${x##*/}"
 			"${PORTAGE_COMPRESS}" ${PORTAGE_COMPRESS_FLAGS} -f "${x}"
 		fi
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/prepman b/pkgcore/ebuild/eapi-bash/helpers/common/prepman
--- a/pkgcore/ebuild/eapi-bash/helpers/common/prepman
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/prepman
@@ -4,24 +4,24 @@
 # Distributed under the terms of the GNU General Public License v2
 
 shopt -s extdebug
-source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+source "${PKGCORE_BIN_PATH}"/exit-handling.lib || { echo "failed loading libs"; exit -127; }
 
 if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
-	ED="${D}"
-elif [[ "${ED:-unset}" == "unset" ]]; then
+	ED=${D}
+elif [[ ${ED:-unset} == "unset" ]]; then
 	echo "The variable ED is missing from the environment, but is required for prefix mode; failing."
 	exit -1
 fi
 
-if [[ -z "$1" ]]; then
-	z="${ED}usr/share/man"
+if [[ -z $1 ]]; then
+	z=${ED}usr/share/man
 else
-	z="${ED}$1/man"
+	z=${ED}$1/man
 fi
 
-[[ ! -d "${z}" ]] && exit 0
+[[ ! -d ${z} ]] && exit 0
 
-if [[ -z "${PORTAGE_COMPRESS_SUFFIX}" ]]; then
+if [[ -z ${PORTAGE_COMPRESS_SUFFIX} ]]; then
 	case ${PORTAGE_COMPRESS} in
 		gzip)  suffix="gz";;
 		bzip2) suffix="bz2";;
@@ -31,37 +31,37 @@ if [[ -z "${PORTAGE_COMPRESS_SUFFIX}" ]]; then
 	esac
 fi
 
-if [[ -z "${prepallman_banner}" ]]; then
+if [[ -z ${prepallman_banner} ]]; then
 	echo "man: ${PORTAGE_COMPRESS} ${PORTAGE_COMPRESS_FLAGS}"
 fi
 
-for x in `find "${z}"/ -type d 2>/dev/null` ; do
-	for y in `find "${x}"/ \( -type f -or -type l \) ! -name '.keep*' -maxdepth 1 -mindepth 1 2>/dev/null` ; do
-		if [[ -L "${y}" ]]; then
+for x in $(find "${z}"/ -type d 2>/dev/null); do
+	for y in $(find "${x}"/ \( -type f -or -type l \) ! -name '.keep*' -maxdepth 1 -mindepth 1 2>/dev/null); do
+		if [[ -L ${y} ]]; then
 			# Symlink ...
 			mylink=${y}
 			linkto=$(readlink "${y}")
 
 			# Do NOT change links to directories
-			if [[ -d "${z}/${linkto}" ]]; then
+			if [[ -d ${z}/${linkto} ]]; then
 				continue
 			fi
 
-			if [[ "${linkto##*.}" != "${suffix}" ]]; then
-				linkto="${linkto}.${suffix}"
+			if [[ ${linkto##*.} != ${suffix} ]]; then
+				linkto=${linkto}.${suffix}
 			fi
-			if [[ "${mylink##*.}" != "${suffix}" ]]; then
-				mylink="${mylink}.${suffix}"
+			if [[ ${mylink##*.} != ${suffix} ]]; then
+				mylink=${mylink}.${suffix}
 			fi
 
 			echo "   link fixed ${mylink##*/}"
 			ln -snf "${linkto}" "${mylink}"
-			if [[ "${y}" != "${mylink}" ]]; then
+			if [[ ${y} != ${mylink} ]]; then
 				echo "   link removed ${y##*/}"
 				rm -f "${y}"
 			fi
 		else
-			if [[ "${y##*.}" != "${suffix}" ]] && [[ ! -d "${y}" ]] ; then
+			if [[ ${y##*.} != ${suffix} ]] && [[ ! -d ${y} ]]; then
 				echo "   compressing ${y##*/}"
 				"${PORTAGE_COMPRESS}" ${PORTAGE_COMPRESS_FLAGS} -f "${y}"
 			fi
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/prepstrip b/pkgcore/ebuild/eapi-bash/helpers/common/prepstrip
--- a/pkgcore/ebuild/eapi-bash/helpers/common/prepstrip
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/prepstrip
@@ -4,7 +4,7 @@
 # Distributed under the terms of the GNU General Public License v2
 
 shopt -s extdebug
-source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+source "${PKGCORE_BIN_PATH}"/exit-handling.lib || { echo "failed loading libs"; exit -127; }
 
 source "${PKGCORE_BIN_PATH}"/isolated-functions.lib || {
 	echo "failed sourcing isolated-functions"
@@ -16,15 +16,15 @@ __feature_is_enabled installsources || exit 0
 __safe_has installsources ${RESTRICT} && exit 0
 
 if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
-	ED="${D}"
-elif [[ "${ED:-unset}" == "unset" ]]; then
+	ED=${D}
+elif [[ ${ED:-unset} == "unset" ]]; then
 	echo "The variable ED is missing from the environment, but is required for prefix mode; failing."
 	exit -1
 fi
 
 for x in debugedit scanelf rsync sort; do
-	if ! type -P $x >/dev/null ; then
-		ewarn "FEATURES=installsources is enabled but the $x binary could not"
+	if ! type -P ${x} >/dev/null; then
+		ewarn "FEATURES=installsources is enabled but the ${x} binary could not"
 	    ewarn "be found. This feature will not work unless debugedit is installed!"
 		exit 0
 	fi
@@ -35,7 +35,7 @@ save_elf_sources() {
 	local sources_dir=/usr/src/debug/${CATEGORY}/${PF}
 	debugedit -b "${WORKDIR}" -d "${sources_dir}" \
 		-l "${T}"/debug.sources "${x}"
-	if [[ -s ${T}/debug.sources ]] ; then
+	if [[ -s ${T}/debug.sources ]]; then
 		[[ -d ${ED}${sources_dir} ]] || mkdir -p "${ED}${sources_dir}"
 		grep -zv '/<built-in>$' "${T}"/debug.sources | \
 			(cd "${WORKDIR}"; LANG=C sort -z -u | \
@@ -47,9 +47,9 @@ save_elf_sources() {
 # We want to log already stripped binaries, as this may be a QA violation.
 # They prevent us from getting the splitdebug data.
 if ! __safe_has binchecks ${RESTRICT} && \
-	! __safe_has strip ${RESTRICT} ; then
+	! __safe_has strip ${RESTRICT}; then
 	f=$(scanelf -yqRBF '#k%F' -k '!.symtab' "$@")
-	if [[ -n ${f} ]] ; then
+	if [[ -n ${f} ]]; then
 		echo -e "\a\n"
 		ewarn "QA Notice: Pre-stripped files found:"
 		ewarn "${f}"
@@ -58,9 +58,7 @@ if ! __safe_has binchecks ${RESTRICT} && \
 fi
 
 # Now we look for unstripped binaries.
-for x in \
-	$(scanelf -yqRBF '#k%F' -k '.symtab' "$@")
-do
+for x in $(scanelf -yqRBF '#k%F' -k '.symtab' "$@"); do
 	f=$(file "${x}") || continue
 	[[ -z ${f} ]] && continue
 
@@ -70,9 +68,9 @@ do
 	# actually causes problems.  install sources for all
 	# elf types though cause that stuff is good.
 
-	if [[ ${f} == *"SB executable"* || ${f} == *"SB shared object"* ]] ; then
+	if [[ ${f} == *"SB executable"* || ${f} == *"SB shared object"* ]]; then
 		save_elf_sources "${x}"
-	elif [[ ${f} == *"SB relocatable"* ]] ; then
+	elif [[ ${f} == *"SB relocatable"* ]]; then
 		save_elf_sources "${x}"
 	fi
 done
diff --git a/pkgcore/ebuild/eapi-bash/helpers/internals/prepall b/pkgcore/ebuild/eapi-bash/helpers/internals/prepall
--- a/pkgcore/ebuild/eapi-bash/helpers/internals/prepall
+++ b/pkgcore/ebuild/eapi-bash/helpers/internals/prepall
@@ -3,15 +3,15 @@
 # Copyright: 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
-source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+source "${PKGCORE_BIN_PATH}"/exit-handling.lib || { echo "failed loading libs"; exit -127; }
 
-"${PKGCORE_BIN_PATH}/helpers/internals/prepallman"
+"${PKGCORE_BIN_PATH}"/helpers/internals/prepallman
 prepinfo
 prepallstrip
 
 if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
-	ED="${D}"
-elif [[ "${ED:-unset}" == "unset" ]]; then
+	ED=${D}
+elif [[ ${ED:-unset} == "unset" ]]; then
 	echo "The variable ED is missing from the environment, but is required for prefix mode; failing."
 	exit -1
 fi
@@ -19,12 +19,12 @@ fi
 # this should help to ensure that all (most?) shared libraries are executable
 # and that all libtool scripts / static libraries are not executable
 for i in "${ED}"opt/*/lib{,32,64} \
-		"${ED}"lib{,32,64}       \
-		"${ED}"usr/lib{,32,64}   \
-		"${ED}"usr/X11R6/lib{,32,64} ; do
+		 "${ED}"lib{,32,64}       \
+		 "${ED}"usr/lib{,32,64}   \
+		 "${ED}"usr/X11R6/lib{,32,64}; do
 	[[ ! -d ${i} ]] && continue
 
-	for j in "${i}"/*.so.* "${i}"/*.so ; do
+	for j in "${i}"/*.so.* "${i}"/*.so; do
 		[[ ! -e ${j} ]] && continue
 		[[ -L ${j} ]] && continue
 		[[ -x ${j} ]] && continue
@@ -32,7 +32,7 @@ for i in "${ED}"opt/*/lib{,32,64} \
 		chmod +x "${j}"
 	done
 
-	for j in "${i}"/*.a "${i}"/*.la ; do
+	for j in "${i}"/*.a "${i}"/*.la; do
 		[[ ! -e ${j} ]] && continue
 		[[ -L ${j} ]] && continue
 		[[ ! -x ${j} ]] && continue
@@ -45,11 +45,11 @@ done
 # /lib, we have to make sure we have a linker script in /usr/lib along side
 # the static library, or gcc will utilize the static lib when linking :(.
 # http://bugs.gentoo.org/4411
-for a in "${ED}"usr/lib*/*.a ; do
+for a in "${ED}"usr/lib*/*.a; do
 	s=${a%.a}.so
-	if [[ ! -e ${s} ]] ; then
+	if [[ ! -e ${s} ]]; then
 		s=${s%usr/*}${s##*/usr/}
-		if [[ -e ${s} ]] ; then
+		if [[ -e ${s} ]]; then
 			echo -e "\aQA Notice: missing gen_usr_ldscript for ${s##*/}\a"
  			sleep 1
 		fi
@@ -58,34 +58,34 @@ done
 
 # Make sure people don't store libtool files or static libs in /lib
 f=$(ls "${ED}"lib*/*.{a,la} 2>/dev/null)
-if [[ -n ${f} ]] ; then
+if [[ -n ${f} ]]; then
 	echo -e "\n\aQA Notice: excessive files found in the / partition\a"
 	echo "${f}"
 	sleep 1
 fi
 
 # Verify that the libtool files don't contain bogus $ED entries.
-for a in "${ED}"usr/lib*/*.la ; do
+for a in "${ED}"usr/lib*/*.la; do
 	s=${a##*/}
-	if grep -qs "${ED}" "${a}" ; then
+	if grep -qs "${ED}" "${a}"; then
 		echo -e "\n\aQA Notice: ${s} appears to contain PORTAGE_TMPDIR paths\a"
 		sleep 1
 	fi
 done
 
-if type -p scanelf > /dev/null ; then
+if type -p scanelf > /dev/null; then
 
 # Run some sanity checks on shared libraries
-for d in "${ED}"lib* "${ED}"usr/lib* ; do
+for d in "${ED}"lib* "${ED}"usr/lib*; do
 	f=$(scanelf -ByF '%S %p' "${d}"/lib*.so* | gawk '$2 == "" { print }')
-	if [[ -n ${f} ]] ; then
+	if [[ -n ${f} ]]; then
 		echo -e "\n\aQA Notice: the following shared libraries lack a SONAME\a"
 		echo "${f}"
 		sleep 1
 	fi
 
 	f=$(scanelf -ByF '%n %p' "${d}"/lib*.so* | gawk '$2 == "" { print }')
-	if [[ -n ${f} ]] ; then
+	if [[ -n ${f} ]]; then
 		echo -e "\n\aQA Notice: the following shared libraries lack NEEDED entries\a"
 		echo "${f}"
 		sleep 1
diff --git a/pkgcore/ebuild/eapi-bash/helpers/internals/prepallman b/pkgcore/ebuild/eapi-bash/helpers/internals/prepallman
--- a/pkgcore/ebuild/eapi-bash/helpers/internals/prepallman
+++ b/pkgcore/ebuild/eapi-bash/helpers/internals/prepallman
@@ -3,16 +3,16 @@
 # Distributed under the terms of the GNU General Public License v2
 
 shopt -s extdebug
-source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
+source "${PKGCORE_BIN_PATH}"/exit-handling.lib || { echo "failed loading libs"; exit -127; }
 
 if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
-	ED="${D}"
-elif [[ "${ED:-unset}" == "unset" ]]; then
+	ED=${D}
+elif [[ ${ED:-unset} == "unset" ]]; then
 	echo "The variable ED is missing from the environment, but is required for prefix mode; failing."
 	exit -1
 fi
 
-for x in $(find "${ED}" -name man -type d -printf '%P\n') ; do
+for x in $(find "${ED}" -name man -type d -printf '%P\n'); do
 	prepman ${x%/man}
-	export prepallman_banner=no
+	export prepallman_banner="no"
 done
