explicitly define ED=D for all consumer scripts for < EAPI-3
This fixes sandbox failures during gcc installs where prepinfo tries to
remove GNU info files from the live filesystem instead of the D because
the ebuilds use < EAPI-3 where ED isn't defined.

diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo b/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo
--- a/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/prepinfo
@@ -6,6 +6,13 @@
 shopt -s extdebug
 source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }
 
+if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
+	ED="${D}"
+elif [[ "${ED:-unset}" == "unset" ]]; then
+	echo "The variable ED is missing from the environment, but is required for prefix mode; failing."
+	exit -1
+fi
+
 if [[ -z "$1" ]]; then
 	z="${ED}usr/share/info"
 else
diff --git a/pkgcore/ebuild/eapi-bash/helpers/common/prepstrip b/pkgcore/ebuild/eapi-bash/helpers/common/prepstrip
--- a/pkgcore/ebuild/eapi-bash/helpers/common/prepstrip
+++ b/pkgcore/ebuild/eapi-bash/helpers/common/prepstrip
@@ -15,6 +15,13 @@ source "${PKGCORE_BIN_PATH}"/isolated-functions.lib || {
 __feature_is_enabled installsources || exit 0
 __safe_has installsources ${RESTRICT} && exit 0
 
+if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
+	ED="${D}"
+elif [[ "${ED:-unset}" == "unset" ]]; then
+	echo "The variable ED is missing from the environment, but is required for prefix mode; failing."
+	exit -1
+fi
+
 for x in debugedit scanelf rsync sort; do
 	if ! type -P $x >/dev/null ; then
 		ewarn "FEATURES=installsources is enabled but the $x binary could not"
diff --git a/pkgcore/ebuild/eapi-bash/helpers/internals/prepall b/pkgcore/ebuild/eapi-bash/helpers/internals/prepall
--- a/pkgcore/ebuild/eapi-bash/helpers/internals/prepall
+++ b/pkgcore/ebuild/eapi-bash/helpers/internals/prepall
@@ -9,10 +9,10 @@ source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; 
 prepinfo
 prepallstrip
 
-if ! ${PKGCORE_PREFIX_SUPPORT=false}; then
-	export ED="${D}"
+if ! ${PKGCORE_PREFIX_SUPPORT:=false}; then
+	ED="${D}"
 elif [[ "${ED:-unset}" == "unset" ]]; then
-	echo "The variable ED is missing from the environment of prepall; failing."
+	echo "The variable ED is missing from the environment, but is required for prefix mode; failing."
 	exit -1
 fi
 
