removal of non pms compliant functions that were hold overs from the early ebd/saviour/portage-3 days, misc renames to be more explicit about the bash dependency (and consistant in naming), finally leave a sym in place for any potential upgrade issues involving invocation of ebuild-daemon

diff --git a/pkgcore/bin/ebuild-helpers/doman b/pkgcore/bin/ebuild-helpers/doman
--- a/pkgcore/bin/ebuild-helpers/doman
+++ b/pkgcore/bin/ebuild-helpers/doman
@@ -6,7 +6,10 @@ if [ -z "${PKGCORE_BIN_PATH}" ]; then
 	echo "PKGCORE_BIN_PATH is unset!"
 	exit -1
 fi
-source "${PKGCORE_BIN_PATH}/isolated-functions.sh"
+source "${PKGCORE_BIN_PATH}/isolated-functions.bash" || {
+	echo "failed sourcing isolated-functions"
+	exit -1
+}
 
 if [[ $# -lt 1 ]] ; then
 	echo "$0: at least one argument needed" 1>&2
