ebd/generate_eapi_lib: allow sourcing and running as a function
Since it needs to be run in the global scope for git repos where
external commands are disabled so bash can't run the script normally.

diff --git a/ebd/generate_eapi_lib b/ebd/generate_eapi_lib
--- a/ebd/generate_eapi_lib
+++ b/ebd/generate_eapi_lib
@@ -7,42 +7,60 @@
 # different support to be enabled or overridden. For installed versions, static
 # function lists are generated at install time and used instead.
 
-SCOPE=global
-while getopts "s:" opt; do
-	case ${opt} in
-		s) SCOPE=${OPTARG} ;;
-		*) exit 1 ;;
-	esac
-done
+load_eapi_libs() {
+	local scope=global
+	local -a skip_funcs=( $(compgen -A function) )
+	local skip_regex=$(IFS='|'; echo "^(${skip_funcs[*]})$")
 
-shift $((OPTIND-1))
-EAPI=${1:-0}
-FUNC=$2
-export PKGCORE_EBD_PATH=${BASH_SOURCE[0]%/*}
+	while getopts "s:" opt; do
+		case ${opt} in
+			s) scope=${OPTARG} ;;
+			*) exit 1 ;;
+		esac
+	done
+	shift $((OPTIND-1))
+	local EAPI=${1:-0}
+	local selected_func=$2
 
-# without this var, parsing certain things can fail; force to true if unset or
-# null so any code that tried accessing it thinks it succeeded
-export PKGCORE_PYTHON_BINARY=${PKGCORE_PYTHON_BINARY:-/bin/true}
+	local eapi file func
+	for (( eapi=0 ; eapi<=${EAPI} ; eapi++ )) ; do
+		# load generic phase scope lib when targeting a specific phase
+		if [[ ${scope} != global && ${scope} != phase ]]; then
+			file=${PKGCORE_EBD_PATH}/eapi/${eapi}/phase.bash
+			if  [[ -f ${file} ]]; then
+				source "${file}" || { echo "failed loading ${file}" >&2; exit 1; }
+			fi
+		fi
 
-for (( eapi=0 ; eapi<=${EAPI} ; eapi++ )) ; do
-	# load generic phase scope lib when targeting a specific phase
-	if [[ ${SCOPE} != global && ${SCOPE} != phase ]]; then
-		file=${PKGCORE_EBD_PATH}/eapi/${eapi}/phase.bash
+		file=${PKGCORE_EBD_PATH}/eapi/${eapi}/${scope}.bash
 		if  [[ -f ${file} ]]; then
 			source "${file}" || { echo "failed loading ${file}" >&2; exit 1; }
 		fi
-	fi
 
-	file=${PKGCORE_EBD_PATH}/eapi/${eapi}/${SCOPE}.bash
-	if  [[ -f ${file} ]]; then
-		source "${file}" || { echo "failed loading ${file}" >&2; exit 1; }
-	fi
-
-	# replace EAPI banned functions if any exist
-	for func in "${PKGCORE_BANNED_FUNCS[@]}"; do
-		eval "${func}() { die \"\${FUNCNAME}: banned in EAPI ${eapi}\"; }"
+		# replace EAPI banned functions if any exist
+		for func in "${PKGCORE_BANNED_FUNCS[@]}"; do
+			eval "${func}() { die \"\${FUNCNAME}: banned in EAPI ${eapi}\"; }"
+		done
+		unset PKGCORE_BANNED_FUNCS
 	done
-	unset PKGCORE_BANNED_FUNCS
-done
 
-declare -f ${FUNC}
+	local -a eapi_funcs
+	for func in $(compgen -A function); do
+		[[ ! ${func} =~ ${skip_regex} ]] && eapi_funcs+=( ${func} )
+	done
+
+	if [[ -n ${selected_func} && ! ${selected_func} =~ ${skip_regex} ]]; then
+		declare -f ${selected_func}
+	else
+		declare -f ${eapi_funcs[@]}
+	fi
+}
+
+# output values if being run as a script
+if [[ ${BASH_SOURCE[0]} == $0 ]]; then
+	export PKGCORE_EBD_PATH=${BASH_SOURCE[0]%/*}
+	# without this var, parsing certain things can fail; force to true if unset or
+	# null so any code that tried accessing it thinks it succeeded
+	export PKGCORE_PYTHON_BINARY=${PKGCORE_PYTHON_BINARY:-/bin/true}
+	load_eapi_libs "$@"
+fi
