ebd: massive restructure to only define phase functions inside phases
As per the spec. Note this will make the commands return unknown command
errors when run in global scope.

With a few exceptions being exit handing functions (die, assert), output
related (eerror, ewarn, einfo, etc), and debug handling (debug-print*)
as all those are used internally and not worth renaming or otherwise
limiting to phase scope.

diff --git a/ebd/generate_eapi_func_list b/ebd/generate_eapi_func_list
--- a/ebd/generate_eapi_func_list
+++ b/ebd/generate_eapi_func_list
@@ -31,12 +31,16 @@ if ${ONLY}; then
 	if [[ -f "${PKGCORE_EBD_PATH}/eapi/${PREV_EAPI}.bash" ]]; then
 		source "${PKGCORE_EBD_PATH}/eapi/${PREV_EAPI}.bash" \
 			|| { echo "failed loading eapi/${PREV_EAPI}.bash" >&2; exit 1; }
+		source "${PKGCORE_EBD_PATH}/eapi/${PREV_EAPI}-phase.bash" \
+			|| { echo "failed loading eapi/${PREV_EAPI}-phase.bash" >&2; exit 1; }
 		PREV_EAPI_FUNCS=( $(compgen -A function) )
 	fi
 fi
 
 source "${PKGCORE_EBD_PATH}/eapi/${EAPI}.bash" \
 	|| { echo "failed loading eapi/${EAPI}.bash" >&2; exit 1; }
+source "${PKGCORE_EBD_PATH}/eapi/${EAPI}-phase.bash" \
+	|| { echo "failed loading eapi/${EAPI}-phase.bash" >&2; exit 1; }
 
 if ${ONLY}; then
 	for func in "${PREV_EAPI_FUNCS[@]}"; do
