ebd: load the generic phase scope lib when generating specific phase scope libs
Cuts a required source command during phase init.

diff --git a/ebd/generate_eapi_lib b/ebd/generate_eapi_lib
--- a/ebd/generate_eapi_lib
+++ b/ebd/generate_eapi_lib
@@ -25,7 +25,14 @@ export PKGCORE_EBD_PATH=${BASH_SOURCE[0]%/*}
 export PKGCORE_PYTHON_BINARY=${PKGCORE_PYTHON_BINARY:-/bin/true}
 
 for (( eapi=0 ; eapi<=${EAPI} ; eapi++ )) ; do
-	file="${PKGCORE_EBD_PATH}/eapi/${eapi}"/${SCOPE}.bash
+	# load generic phase scope lib when targeting a specific phase
+	if [[ ${SCOPE} != global && ${SCOPE} != phase ]]; then
+		file=${PKGCORE_EBD_PATH}/eapi/${eapi}/phase.bash
+		if  [[ -f ${file} ]]; then
+			source "${file}" || { echo "failed loading ${file}" >&2; exit 1; }
+		fi
+	fi
+	file=${PKGCORE_EBD_PATH}/eapi/${eapi}/${SCOPE}.bash
 	if  [[ -f ${file} ]]; then
 		source "${file}" || { echo "failed loading ${file}" >&2; exit 1; }
 	fi
