EAPI=9: fix ebd loading of banned assert
Signed-off-by: Arthur Zamarin <arthurzam@gentoo.org>

diff --git a/data/lib/pkgcore/ebd/generate_eapi_lib b/data/lib/pkgcore/ebd/generate_eapi_lib
--- a/data/lib/pkgcore/ebd/generate_eapi_lib
+++ b/data/lib/pkgcore/ebd/generate_eapi_lib
@@ -8,6 +8,8 @@
 # function lists are generated at install time and used instead.
 
 load_eapi_libs() {
+	source "${PKGCORE_EBD_PATH}"/exit-handling.bash >&2 || { echo "ERROR: failed sourcing exit-handling.bash"; exit -1; }
+
 	local scope="global"
 	local -a skip_funcs=( $(compgen -A function) )
 	local skip_regex=$(IFS='|'; echo "^(${skip_funcs[*]})$")
