refactor(tests): run against the last release of the revdep target.
Signed-off-by: Brian Harring <ferringb@gmail.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -85,8 +85,12 @@ jobs:
       with:
         files: ./coverage.xml
 
-  pkgcheck-test:
+  revdep:
     runs-on: ubuntu-latest
+    continue-on-error: true
+    strategy:
+      matrix:
+        repo: ['pkgcheck', 'pkgdev']
     steps:
     - name: Checkout pkgcore
       uses: pkgcore/gh-actions/get-source@main
@@ -94,11 +98,24 @@ jobs:
         artifact-id: ${{ inputs.release-artifact-id }}
         path: pkgcore
 
-    - name: Checkout pkgcheck
+    - name: Find last ${{ matrix.repo }} release
+      run: |
+        versions=$(git ls-remote -q --refs https://github.com/pkgcore/${{ matrix.repo }}  | \
+          sed -nre 's:.*refs/tags/(.+)$:\1:p' | \
+          sort -V)
+        echo found versions:
+        echo "${versions}"
+        latest=$(echo "$versions" | tail -n 1)
+        echo "latest=${latest}"
+        [ -z "$latest" ] && { echo "failed finding the tag"; exit 1; }
+        echo "LATEST_TAG=$latest" >> $GITHUB_ENV
+
+    - name: Checkout ${{ matrix.repo }} ${{ env.LATEST_TAG }}
       uses: actions/checkout@v5
       with:
-        repository: pkgcore/pkgcheck
-        path: pkgcheck
+        repository: pkgcore/${{ matrix.repo }}
+        path: ${{ matrix.repo }}
+        ref: refs/tags/${{ env.LATEST_TAG }}
 
     - name: Set up Python 3.13
       uses: actions/setup-python@v5
@@ -107,51 +124,16 @@ jobs:
         cache: 'pip'
         cache-dependency-path: |
           pkgcore/pyproject.toml
-          pkgcheck/pyproject.toml
+          ${{ matrix.repo }}/pyproject.toml
 
     - name: Install pip dependencies
       run: |
         python -m pip install --upgrade pip
         pip install "./pkgcore"
-        pip install "./pkgcheck[test]"
+        pip install "./${{ matrix.repo }}[test]"
 
     - name: Test with pytest
-      working-directory: ./pkgcheck
-      env:
-        PY_COLORS: 1 # forcibly enable pytest colors
-      run: pytest -v
-
-  pkgdev-test:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout pkgcore
-      uses: pkgcore/gh-actions/get-source@main
-      with:
-        artifact-id: ${{ inputs.release-artifact-id }}
-        path: pkgcore
-    - name: Checkout pkgdev
-      uses: actions/checkout@v5
-      with:
-        repository: pkgcore/pkgdev
-        path: pkgdev
-
-    - name: Set up Python 3.13
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.13'
-        cache: 'pip'
-        cache-dependency-path: |
-          pkgcore/pyproject.toml
-          pkgdev/pyproject.toml
-
-    - name: Install pip dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install "./pkgcore"
-        pip install "./pkgdev[test]"
-
-    - name: Test with pytest
-      working-directory: ./pkgdev
+      working-directory: ./${{ matrix.repo }}
       env:
         PY_COLORS: 1 # forcibly enable pytest colors
       run: pytest -v
